services:
  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "${POSTGRES_PATH}/postgres/data:/var/lib/postgresql/data"
      - "${POSTGRES_PATH}/postgres/init-scripts:/docker-entrypoint-initdb.d"
      - "${POSTGRES_PATH}/postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf"

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    platform: linux/x86_64
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
#      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
#      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
#    volumes:
#      - "${RABBITMQ_PATH}/rabbitmq/data:/var/lib/rabbitmq"
#      - "${RABBITMQ_PATH}/rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
#      - "${RABBITMQ_PATH}/rabbitmq/conf/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  certificate-stream:
    container_name: certificate-stream
    build:
      context: "services/certificate-stream"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_CERTSTREAM_DB}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${CONFIG_PATH}/:/config/:ro"
      - "${SERVICES_PATH}/commons/:/app/src/commons/:ro"

  certificate-processor:
    container_name: certificate-processor
    build:
      context: "services/certificate-processor"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
#      POSTGRES_DB: "${POSTGRES_CERTPROCESSOR_DB}"
#      RABBITMQ_HOST: "${RABBITMQ_HOST}"
#      RABBITMQ_PORT: "${RABBITMQ_PORT}"
#      RABBITMQ_USER: "${RABBITMQ_DEFAULT_USER}"
#      RABBITMQ_PASS: "${RABBITMQ_DEFAULT_PASS}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${CONFIG_PATH}/:/config/:ro"

networks:
  default:
    external: true
    name: "certificate-watcher-net"